schema:
  format:
    openapi: "3.0.0"
  service_input_type: "LoadBalancedServiceInput"
  pipeline_input_type: "PipelineInputs"

  types:
    LoadBalancedServiceInput:
      type: object
      description: "Input properties for a loadbalanced EC2 service"
      properties:
        instance_size:
          type: string
          description: "The size of the instance you want to run"
          enum: ["x-small", "small", "medium"]
          default: "x-small"
        manage_accountid:
          type: string
          description: "Management account ID"
          minLength: 12
          maxLength: 12
          default: ""

    PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        memo:
          type: string
          description: "This is a test item"
          default: "memo"
          minLength: 1
          maxLength: 100
        environment_accountid:
          description: "Environment account ID"
          type: string
          minLength: 12
          maxLength: 12
          default: ""
          